services:
  - type: web
    name: web-scraper-backend
    env: node
    buildCommand: |
      apt-get update && apt-get install -y chromium-browser fonts-liberation
      npm install --omit=dev
    startCommand: node server.js